_target_: models.detr.DETR3d_V1
num_classes: 6
num_queries: 2
aux_loss: false
transformer: null

backbone:
  _target_: models.backbone.Joiner
  backbone:
    _target_: models.backbone.Backbone
    num_channels: 512
    backbone:
      _target_: torchvision.models._utils.IntermediateLayerGetter
      return_layers:
        layer4: 0
      model:
        _target_: models.resnet.ResNet3D
        stem:
          _target_: models.resnet.stem
          name: basic_res
        block:
          _target_: models.resnet.block
          name: basic_res
        layers: [2, 2, 2, 2]

  position_embedding:
    _target_: models.position_encoding.PositionEmbeddingSine3d
    hidden_dim: 6 #d_model // 3
    normalize: True
