defaults:
  - model: detr_3d
  - data: oai

# MODEL
device: cuda
checkpoint: false # path to the checkpoint
state_dict: outputs/2021-07-10/10-44-20/best_model.pt

# TESTING
eval: false # only run evaluation (uses test set)
cam: true # run grad cam for menisci (ignored if eval is false)
meniscus: [0, 1] # run grad cam for these menisci (ignored if eval is false or cam is false)
metrics:
  - balanced_accuracy
  - roc_curve
  - roc_auc_score
  - precision_recall_curve
  - confusion_matrix

# CRITERION
weights:
  labels: 1
  boxes: 5
  giou: 2
  inter: 1

# TRAINING SETTINGS & HPARAMS
num_epochs: 300
batch_size: 4
num_workers: 4
lr: 0.001 # default learning rate
lr_backbone: 0.001 # cnn learning rate
lr_drop_step: 50
lr_drop_rate: 0.5
window: 20
