defaults:
  - model: vidnet

# MODEL
device: cuda
checkpoint: false # path to the checkpoint
state_dict: false # path to the model state_dict (overrides model state_dict in checkpoint)
eval: false # only run evaluation (uses test set)

# model:
#   cls_tokens: 1
#   cls_out: 2
#   box_out: 12

# CRITERION
weights:
  labels: 1
  # boxes: 2
  # giou: 1

# DATA
data_dir: oai/v00/data/inputs
anns_dir: meniscaltears/data
binary: true
multilabel: False
limit_train_items: false # will take up to limit_train_items training examples
limit_val_items: false # will take up to limit_train_items validation examples

# TRAINING HPARAMS
num_epochs: 500
num_workers: 8
batch_size: 4
lr: 0.001
lr_drop_step: 50
lr_drop_rate: 0.5
window: 20
