defaults:
  - model: resnet18

# MODEL
device: cpu
checkpoint: false # path to the checkpoint
state_dict: /scratch/visual/ashestak/meniscaltears/best_models/resnet18/best_model.pt # path to the model state_dict (overrides model state_dict in checkpoint)
eval: false # only run evaluation (uses test set)

# CRITERION
weights:
  labels: 1
  boxes: 5
  giou: 2

# DATA
data_dir: oai/v00/data/inputs
anns_dir: meniscaltears/data
binary: true
multilabel: true
limit_train_items: false # will take up to limit_train_items training examples
limit_val_items: false # will take up to limit_train_items validation examples

# TRAINING HPARAMS
num_epochs: 500
num_workers: 8
batch_size: 4
lr_backbone: 0.001
lr_head: 0.001
lr_drop_step: 50
lr_drop_rate: 0.5
window: 20
