defaults:
  - model: resnet18_cropped

# MODEL
device: cuda
checkpoint: false # path to the checkpoint
state_dict: false # path to the model state_dict (overrides model state_dict in checkpoint)
load_mlp: true # if false will omit cls_out and box_out and only load backbone state_dict
eval: false # only run evaluation (uses test set)
eval_img: null # path to a specific image to evaluate
cam: true # run grad cam for menisci (ignored if eval is false)
meniscus: [0, 1] # run grad cam for these menisci (ignored if eval is false or cam is false)
metrics:
  - balanced_accuracy
  - roc_curve
  - roc_auc_score
  - precision_recall_curve
  - confusion_matrix

crop: true

# CRITERION
weights:
  labels: 1 # will only compute binary_cross_entropy_with_logits loss

# DATA 
root: /scratch/htc/ashestak
data_dir: oai/v00/data/inputs
anns_dir: meniscaltears/data
binary: true
multilabel: true

limit_train_items: false # will take up to limit_train_items training examples
limit_val_items: false # will take up to limit_train_items validation examples
limit_test_items: false


# TRAINING HPARAMS
num_epochs: 500
num_workers: 8
batch_size: 16
lr: 0.0001 # default learning rate
lr_backbone: 0.0001
lr_head: 0.0001
lr_drop_step: 50
lr_drop_rate: 0.5
window: 20
