defaults:
  - model: detr_3d
  - data: oai

# MODEL
device: cuda
checkpoint: false # path to the checkpoint
state_dict: /scratch/visual/ashestak/meniscaltears/selected_models/resnet50_baseline/best_model.pt # path to the model state_dict (overrides model state_dict in checkpoint)

# TESTING
eval: false # only run evaluation (uses test set)
cam: true # run grad cam for menisci (ignored if eval is false)
meniscus: [0, 1] # run grad cam for these menisci (ignored if eval is false or cam is false)
metrics:
  - balanced_accuracy
  - roc_curve
  - roc_auc_score
  - precision_recall_curve
  - confusion_matrix

# CRITERION
weights:
  labels: 1
  boxes: 5
  giou: 2

# TRAINING HPARAMS
num_epochs: 500
batch_size: 4
num_workers: 4
lr: 0.0001 # default learning rate
lr_transformer: 0.001 # transformer learning rate
lr_backbone: 0.001 # cnn learning rate
lr_head: 0.001 # mlp learning rate
lr_drop_step: 50
lr_drop_rate: 0.5
window: 20
