defaults:
  - model: resnet18_detr 
  - data: oai
  - override hydra/sweeper: ax

# MODEL
device: cuda
checkpoint: false # path to the checkpoint
state_dict: /scratch/htc/ashestak/meniscaltears/outputs/detr18/sweep/9/best_model.pt
backbone_only: true

data:
  setting: region-tear
  limit_train_items: 400

model:
  num_classes: 3 # global = 1; region = 3;
  num_queries: 2 # global = 1; meniscus = 2; 
  transformer: 
    nhead: ?? #8
    activation: gelu # "relu"
    num_encoder_layers: ?? # 6
    num_decoder_layers: ?? # 6
    dim_feedforward: ?? # 2048
    dropout: ?? #0.1

# TRAINING SETTINGS & HPARAMS
num_epochs: 60
batch_size: 3
num_workers: 6
lr: ?? # default learning rate
lr_backbone: 0.000005 # cnn learning rate
lr_drop_step: 15
lr_drop_rate: 0.75
window: 20

hydra:
  sweeper:
    # The following part of config is used to setup the Hydra Ax plugin and is optional
    ax_config:

      # max_trials is application-specific. Tune it for your use case
      max_trials: 15

      experiment:
        # Default to minimize, set to false to maximize
        minimize: true

      params:
        lr: 
          type: range
          bounds: [0.0001, 0.0005]
        model.transformer.nhead:
          type: choice
          values: [2, 4, 6]
        model.transformer.num_encoder_layers:
          type: range
          bounds: [2, 6]
        model.transformer.num_decoder_layers:
          type: range
          bounds: [2, 6]
        model.transformer.dim_feedforward:
          type: choice
          values: [256, 512, 1024]
        model.transformer.dropout:
          type: range
          bounds: [0.0, 0.3]

# TESTING
eval: false # only run evaluation (uses test set)
cam: false # run grad cam for menisci (ignored if eval is false)
meniscus: [0, 1] # run grad cam for these menisci (ignored if eval is false or cam is false)
metrics:
  - balanced_accuracy
  - roc_curve
  - roc_auc_score
  - precision_recall_curve
  - confusion_matrix

# CRITERION
weights:
  labels: 1
  boxes: 5
  giou: 2
  # inter: 0.7

