defaults:
  - override hydra/sweeper: ax


model:
  _target_: models.resnet.DetNet3D
  backbone: dilated_resnet26_3d
  cls_output_dim: 6
  cls_hidden_dim: 2048
  cls_num_layers: 3
  det_output_dim: 12
  det_hidden_dim: 2048
  det_num_layers: 3
  det_dropout: ??

  intermediate_layer: layer7
  dropout: ??
  cls_dropout: ??
batch_size: 4 
lr_head: ??
lr_backbone: ??

hydra:
  sweeper:
    # The following part of config is used to setup the Hydra Ax plugin and is optional
    ax_config:

      # max_trials is application-specific. Tune it for your use case
      max_trials: 20

      experiment:
        # Default to minimize, set to false to maximize
        minimize: true

      params:
        model.dropout:
          type: range
          bounds: [0.1, 0.9]
        model.cls_dropout:
          type: range
          bounds: [0.1, 0.9]
        lr_head:
          type: range 
          bounds: [0.01, 0.00001]
        lr_backbone:
          type: range
          bounds: [0.01, 0.00001]


# MODEL
device: cuda
checkpoint: false # path to the checkpoint
state_dict: false # path to the model state_dict (overrides model state_dict in checkpoint)
load_mlp: true # if false will omit cls_out and box_out and only load backbone state_dict
eval: false # only run evaluation (uses test set)
eval_img: null # path to a specific image to evaluate
cam: true # run grad cam for menisci (ignored if eval is false)
meniscus: [0, 1] # run grad cam for these menisci (ignored if eval is false or cam is false)
metrics:
  - balanced_accuracy
  - roc_curve
  - roc_auc_score
  - precision_recall_curve
  - confusion_matrix

crop: false

# CRITERION
weights:
  labels: 1 # will only compute binary_cross_entropy_with_logits loss
  boxes: 1
  giou: 1


# DATA 
root: /scratch/htc/ashestak
data_dir: oai/v00/data/inputs
anns_dir: meniscaltears/data
binary: true
multilabel: true
tse: true
mix: false
data_augmentation: true

limit_train_items: false # will take up to limit_train_items training examples
limit_val_items: false # will take up to limit_train_items validation examples
limit_test_items: false


# TRAINING HPARAMS
num_epochs: 100
num_workers: 8
lr: 0.0001 # default learning rate
lr_drop_step: 50
lr_drop_rate: 0.5
window: 20

