_target_: models.resnet.DetNet3D
backbone: resnet50_3d
dropout: 0.5
cls_output_dim: 6
cls_hidden_dim: 2048
cls_num_layers: 3
cls_dropout: 0.1
det_output_dim: 12
det_hidden_dim: 2048
det_num_layers: 3
det_dropout: 0.1
